apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: game-2048
spec:
  template:
    spec:
      containers:
        # Replace with your docker registry info
        - image: pengbai/docker-supermario
          ports:
            - containerPort: 80
